apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: nginx-controller-pdb
spec:
  minAvailable: {{ .Values.controller.pdbCount }}
  selector:
    matchLabels:
      app: {{ template "nginx-ingress.name" . }}
